# Generated by Django 4.2.7 on 2024-01-03 03:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commodity",
            fields=[
                ("commodity_id", models.AutoField(primary_key=True, serialize=False)),
                ("commodity_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "commodity_img",
                    models.ImageField(null=True, upload_to="commodities/"),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now, null=True),
                ),
                ("date_edited", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "commodity_table",
            },
        ),
    ]
