# Generated by Django 4.2.7 on 2024-01-03 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0003_about"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discussion",
            fields=[
                ("discussion_id", models.AutoField(primary_key=True, serialize=False)),
                ("discussion_title", models.CharField(max_length=255)),
                ("discussion_question", models.TextField()),
                ("likes", models.IntegerField(default=0)),
                ("dislikes", models.IntegerField(default=0)),
                (
                    "date_posted",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("commodity_tag", models.ManyToManyField(to="users_app.commodity")),
            ],
            options={
                "db_table": "discussion&forum_table",
            },
        ),
        migrations.CreateModel(
            name="Reply",
            fields=[
                ("reply_id", models.AutoField(primary_key=True, serialize=False)),
                ("reply_content", models.TextField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users_app.discussion",
                    ),
                ),
            ],
            options={
                "db_table": "reply_table",
            },
        ),
    ]
