# Generated by Django 4.2.7 on 2024-01-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0004_discussion_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussion",
            name="date_posted",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="reply",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
