# Generated by Django 4.2.7 on 2024-01-03 08:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0005_alter_discussion_date_posted_alter_reply_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discussion",
            name="author",
        ),
    ]
