# Generated by Django 4.2.7 on 2024-01-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0006_remove_discussion_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchFrequency",
            fields=[
                ("search_id", models.AutoField(primary_key=True, serialize=False)),
                ("search_term", models.CharField(max_length=255, unique=True)),
                ("frequency", models.IntegerField(default=0)),
                ("date_searched", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "search_analytics_table",
            },
        ),
        migrations.RenameField(
            model_name="reply",
            old_name="discussion",
            new_name="discussion_id",
        ),
    ]
