# Generated by Django 4.2.7 on 2024-01-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0009_alter_searchfrequency_search_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchfrequency",
            name="search_term",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
