# Generated by Django 4.2.7 on 2024-01-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0010_alter_searchfrequency_search_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchfrequency",
            name="frequency",
            field=models.IntegerField(default=1),
        ),
    ]
