# Generated by Django 4.2.7 on 2024-01-05 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0011_alter_searchfrequency_frequency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discussion",
            name="dislikes",
        ),
        migrations.RemoveField(
            model_name="discussion",
            name="likes",
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                ("reaction_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "reaction_type",
                    models.IntegerField(choices=[(1, "Like"), (-1, "Dislike")]),
                ),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users_app.discussion",
                    ),
                ),
            ],
        ),
    ]
