# Generated by Django 4.2.7 on 2024-01-10 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "users_app",
            "0012_remove_discussion_dislikes_remove_discussion_likes_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="FilteredCommodityFrequency",
            fields=[
                ("filter_id", models.AutoField(primary_key=True, serialize=False)),
                ("frequency", models.IntegerField(default=1)),
                ("date_filtered", models.DateTimeField(auto_now=True)),
                (
                    "commodity_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users_app.commodity",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_filtered_commodity_analytics",
            },
        ),
    ]
