# Generated by Django 4.2.7 on 2024-01-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0013_filteredcommodityfrequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchfrequency",
            name="search_term",
            field=models.CharField(max_length=255),
        ),
    ]
