# Generated by Django 4.2.7 on 2024-01-10 05:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0014_alter_searchfrequency_search_term"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchfrequency",
            name="date_searched",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
