# Generated by Django 4.2.7 on 2024-01-10 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0015_alter_searchfrequency_date_searched"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filteredcommodityfrequency",
            old_name="commodity_id",
            new_name="commodity",
        ),
    ]
