# Generated by Django 4.2.7 on 2024-01-10 08:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0016_rename_commodity_id_filteredcommodityfrequency_commodity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filteredcommodityfrequency",
            name="date_filtered",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
