# Generated by Django 4.2.7 on 2024-01-11 05:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0017_alter_filteredcommodityfrequency_date_filtered"),
    ]

    operations = [
        migrations.RenameField(
            model_name="discussion",
            old_name="commodity_tag",
            new_name="commodity_id",
        ),
    ]
