# Generated by Django 4.2.7 on 2024-01-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0019_alter_reaction_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reaction",
            name="reaction_type",
        ),
        migrations.AddField(
            model_name="reaction",
            name="dislike",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="reaction",
            name="like",
            field=models.IntegerField(default=1),
        ),
    ]
