# Generated by Django 4.2.7 on 2024-01-12 02:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0020_remove_reaction_reaction_type_reaction_dislike_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("comment_id", models.AutoField(primary_key=True, serialize=False)),
                ("comment_content", models.TextField()),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "discussion_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users_app.discussion",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_comment",
            },
        ),
        migrations.DeleteModel(
            name="Reply",
        ),
    ]
