# Generated by Django 4.2.7 on 2024-01-12 07:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0022_rename_discussion_id_comment_discussion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="date",
            new_name="date_commented",
        ),
    ]
