# Generated by Django 4.2.7 on 2024-01-18 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0025_knowledgeresources_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
