# Generated by Django 4.2.7 on 2024-01-18 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0027_alter_about_date_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="date_edited",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="discussion",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="knowledgeresources",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
