# Generated by Django 4.2.7 on 2024-01-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0029_alter_customuser_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="discussion",
            name="date_posted",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
