# Generated by Django 4.2.7 on 2024-01-19 03:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0031_alter_customuser_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discussion",
            name="date_posted",
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
