# Generated by Django 4.2.7 on 2024-01-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0032_alter_discussion_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("expert", "Expert"),
                    ("secretariat", "Secretariat"),
                    ("general", "General User"),
                    ("admin", "Admin User"),
                ],
                max_length=20,
            ),
        ),
    ]
