# Generated by Django 4.2.7 on 2024-01-22 00:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0035_comment_commentor_id_reaction_reactor_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="commentor_id",
            new_name="commentor",
        ),
        migrations.RenameField(
            model_name="reaction",
            old_name="reactor_id",
            new_name="reactor",
        ),
    ]
