# Generated by Django 4.2.7 on 2024-01-22 02:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0036_rename_commentor_id_comment_commentor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="commentor",
        ),
    ]
