# Generated by Django 4.2.7 on 2024-01-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0039_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="commodity",
            name="recources_types",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
