# Generated by Django 4.2.7 on 2024-01-23 00:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0040_commodity_recources_types"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commodity",
            old_name="recources_types",
            new_name="recources_type",
        ),
    ]
