# Generated by Django 4.2.7 on 2024-01-23 01:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0041_rename_recources_types_commodity_recources_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commodity",
            old_name="recources_type",
            new_name="resources_type",
        ),
    ]
