# Generated by Django 4.2.7 on 2024-01-23 03:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0042_rename_recources_type_commodity_resources_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_created",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="institution",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="occupation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="position",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("expert", "Expert"),
                    ("secretariat", "Secretariat"),
                    ("general", "General User"),
                    ("admin", "Admin User"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
