# Generated by Django 4.2.7 on 2024-01-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "users_app",
            "0043_alter_customuser_date_created_alter_customuser_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="resources_type",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
