# Generated by Django 4.2.7 on 2024-01-24 07:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0045_alter_discussion_commodity_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CMI",
            fields=[
                ("cmi_id", models.AutoField(primary_key=True, serialize=False)),
                ("cmi_name", models.CharField(max_length=255)),
                ("cmi_meaning", models.CharField(max_length=255)),
                ("cmi_description", models.TextField()),
                ("date_created", models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                "db_table": "tbl_cmi",
            },
        ),
    ]
