# Generated by Django 4.2.7 on 2024-01-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0046_cmi"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmi",
            name="cmi_image",
            field=models.ImageField(null=True, upload_to="cmi/"),
        ),
    ]
