# Generated by Django 4.2.7 on 2024-01-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0047_cmi_cmi_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmi",
            name="address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="cmi",
            name="contact_num",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="cmi",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
