# Generated by Django 4.2.7 on 2024-01-29 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0048_cmi_address_cmi_contact_num_cmi_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projects",
            fields=[
                ("project_id", models.AutoField(primary_key=True, serialize=False)),
                ("project_title", models.CharField(max_length=255)),
                ("project_description", models.TextField()),
                ("project_leader", models.CharField(max_length=255)),
                ("fund_source", models.CharField(max_length=255)),
                (
                    "approved_budget",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "downloaded_budget",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "project_started",
                    models.DateField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "project_ended",
                    models.DateField(default=django.utils.timezone.now, null=True),
                ),
                ("project_status", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "tbl_projects",
            },
        ),
    ]