# Generated by Django 4.2.7 on 2024-01-30 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0051_rename_project_leader_projects_proponent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAttachment",
            fields=[
                ("attachment_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="attachments/"),
                ),
                ("attachment_type", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "tbl_project_attachments",
            },
        ),
        migrations.RemoveField(
            model_name="projects",
            name="project_file",
        ),
        migrations.AddField(
            model_name="projects",
            name="attachments",
            field=models.ManyToManyField(
                blank=True, related_name="projects", to="users_app.projectattachment"
            ),
        ),
    ]
