# Generated by Django 4.2.7 on 2024-01-31 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0052_projectattachment_remove_projects_project_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="downloaded_budget",
        ),
        migrations.CreateModel(
            name="DownloadedBudget",
            fields=[
                ("budget_id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("budget_year", models.IntegerField(default=1)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="downloaded_budgets",
                        to="users_app.projects",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_downloaded_budget",
            },
        ),
    ]
