# Generated by Django 4.2.7 on 2024-01-31 02:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0053_remove_projects_downloaded_budget_downloadedbudget"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="project_type",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="downloadedbudget",
            name="budget_year",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
