# Generated by Django 4.2.7 on 2024-01-31 02:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0054_projects_project_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="downloadedbudget",
            old_name="budget_year",
            new_name="downloaded_date",
        ),
    ]
