# Generated by Django 4.2.7 on 2024-01-31 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0055_rename_budget_year_downloadedbudget_downloaded_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="downloadedbudget",
            name="project",
        ),
        migrations.AddField(
            model_name="projects",
            name="downloaded_budget",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budgets",
                to="users_app.downloadedbudget",
            ),
        ),
    ]
