# Generated by Django 4.2.7 on 2024-01-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0056_remove_downloadedbudget_project_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projects",
            name="downloaded_budget",
        ),
        migrations.AddField(
            model_name="projects",
            name="downloaded_budget",
            field=models.ManyToManyField(
                null=True, related_name="budgets", to="users_app.downloadedbudget"
            ),
        ),
    ]
