# Generated by Django 4.2.7 on 2024-01-31 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0057_remove_projects_downloaded_budget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="downloaded_budget",
            field=models.ManyToManyField(
                related_name="budgets", to="users_app.downloadedbudget"
            ),
        ),
    ]
