# Generated by Django 4.2.7 on 2024-01-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0058_alter_projects_downloaded_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadedbudget",
            name="year",
            field=models.IntegerField(default=1),
        ),
    ]
