# Generated by Django 4.2.7 on 2024-01-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0059_downloadedbudget_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="approved_budget",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="projects",
            name="fund_source",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="projects",
            name="project_status",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="projects",
            name="project_title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="projects",
            name="proponent",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
