# Generated by Django 4.2.7 on 2024-01-31 08:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0062_alter_projects_approved_budget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="approved_budget",
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name="ProjectProponentHistory",
            fields=[
                (
                    "proponent_history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("proponent", models.CharField(max_length=255)),
                (
                    "change_date",
                    models.DateField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users_app.projects",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_proponent_history",
            },
        ),
    ]
