# Generated by Django 4.2.7 on 2024-01-31 08:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0063_alter_projects_approved_budget_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProjectProponentHistory",
        ),
    ]
