# Generated by Django 4.2.7 on 2024-02-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0065_projectproponenthistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programs",
            fields=[
                ("program_id", models.AutoField(primary_key=True, serialize=False)),
                ("program_title", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "tbl_programs",
            },
        ),
    ]
