# Generated by Django 4.2.7 on 2024-02-01 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0066_programs"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="program",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programs",
                to="users_app.programs",
            ),
        ),
    ]
