# Generated by Django 4.2.7 on 2024-02-01 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0067_projects_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="programs",
            name="program_description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
