# Generated by Django 4.2.7 on 2024-02-02 00:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0070_programs_total_downloaded_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="programs",
            name="date_created",
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
