# Generated by Django 4.2.7 on 2024-02-05 00:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0071_programs_date_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="knowledgeresources",
            name="commodity",
        ),
        migrations.CreateModel(
            name="Resources",
            fields=[
                ("resources_id", models.AutoField(primary_key=True, serialize=False)),
                ("resources_title", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="resources/"),
                ),
                (
                    "date_created",
                    models.DateField(default=django.utils.timezone.now, null=True),
                ),
                (
                    "cmi",
                    models.ManyToManyField(
                        blank=True, related_name="under_cmi", to="users_app.cmi"
                    ),
                ),
                (
                    "commodity",
                    models.ManyToManyField(
                        blank=True,
                        related_name="commodity_tag",
                        to="users_app.commodity",
                    ),
                ),
                (
                    "knowledge",
                    models.ManyToManyField(
                        blank=True,
                        related_name="resources_type",
                        to="users_app.knowledgeresources",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_resources",
            },
        ),
    ]
