# Generated by Django 4.2.7 on 2024-02-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0073_resources_images_resources_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resources",
            name="resources_description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
