# Generated by Django 4.2.7 on 2024-02-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0074_resources_resources_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="resources",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="resources",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
