# Generated by Django 4.2.7 on 2024-02-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0075_resources_latitude_resources_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="resources",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
