# Generated by Django 4.2.7 on 2024-02-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0079_editresourcerequest_submitted_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editresourcerequest",
            name="edited_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="editresourcerequest",
            name="edited_title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
