# Generated by Django 4.2.7 on 2024-02-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0080_alter_editresourcerequest_edited_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editresourcerequest",
            name="edited_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
