# Generated by Django 4.2.7 on 2024-02-12 06:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0081_alter_editresourcerequest_edited_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resources",
            name="is_pending_edit",
        ),
    ]
