# Generated by Django 4.2.7 on 2024-02-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0083_remove_editresourcerequest_is_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="editresourcerequest",
            name="request_status",
            field=models.CharField(default="pending", max_length=255),
        ),
    ]
