# Generated by Django 4.2.7 on 2024-02-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0084_editresourcerequest_request_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editresourcerequest",
            name="request_status",
            field=models.CharField(default="Pending", max_length=255),
        ),
    ]
