# Generated by Django 4.2.7 on 2024-02-13 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0085_alter_editresourcerequest_request_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editresourcerequest",
            name="edited_cmi",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users_app.cmi",
            ),
        ),
        migrations.AlterField(
            model_name="editresourcerequest",
            name="edited_commodity",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users_app.commodity",
            ),
        ),
        migrations.AlterField(
            model_name="editresourcerequest",
            name="edited_knowledge",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users_app.knowledgeresources",
            ),
        ),
    ]
