# Generated by Django 4.2.7 on 2024-02-14 05:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0087_resources_training_date_resources_venue_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resources",
            name="webinar_link",
        ),
    ]
