# Generated by Django 4.2.7 on 2024-02-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0088_remove_resources_webinar_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="resources",
            name="contact_num",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="resources",
            name="farm",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
