# Generated by Django 4.2.7 on 2024-02-15 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0090_usefullinks"),
    ]

    operations = [
        migrations.AddField(
            model_name="usefullinks",
            name="date_created",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
