# Generated by Django 4.2.7 on 2024-02-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0091_usefullinks_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmi",
            name="status",
            field=models.CharField(default="Approved", max_length=255),
        ),
        migrations.AddField(
            model_name="commodity",
            name="status",
            field=models.CharField(default="Approved", max_length=255),
        ),
        migrations.AddField(
            model_name="knowledgeresources",
            name="status",
            field=models.CharField(default="Approved", max_length=255),
        ),
    ]
