# Generated by Django 4.2.7 on 2024-02-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0092_cmi_status_commodity_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="editresourcerequest",
            name="edited_cmi",
        ),
        migrations.RemoveField(
            model_name="editresourcerequest",
            name="edited_commodity",
        ),
        migrations.AddField(
            model_name="editresourcerequest",
            name="edited_cmi",
            field=models.ManyToManyField(null=True, to="users_app.cmi"),
        ),
        migrations.AddField(
            model_name="editresourcerequest",
            name="edited_commodity",
            field=models.ManyToManyField(null=True, to="users_app.commodity"),
        ),
    ]
