# Generated by Django 4.2.7 on 2024-02-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0093_remove_editresourcerequest_edited_cmi_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editresourcerequest",
            name="edited_cmi",
            field=models.ManyToManyField(blank=True, to="users_app.cmi"),
        ),
        migrations.AlterField(
            model_name="editresourcerequest",
            name="edited_commodity",
            field=models.ManyToManyField(blank=True, to="users_app.commodity"),
        ),
    ]
