# Generated by Django 4.2.7 on 2024-02-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0094_alter_editresourcerequest_edited_cmi_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                ("carousel_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "img_path",
                    models.ImageField(blank=True, null=True, upload_to="carousel/"),
                ),
            ],
            options={
                "db_table": "tbl_carousel",
            },
        ),
    ]
