# Generated by Django 4.2.7 on 2024-02-21 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0095_carousel"),
    ]

    operations = [
        migrations.AddField(
            model_name="carousel",
            name="alt",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
