# Generated by Django 4.2.7 on 2024-02-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0097_carousel_commodity"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeSearch",
            fields=[
                ("search_id", models.AutoField(primary_key=True, serialize=False)),
                ("contents", models.TextField()),
                ("keywords", models.CharField(max_length=255)),
                ("knowledge", models.TextField()),
                ("resources_type", models.CharField(max_length=50)),
                ("search_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "tbl_home_search",
            },
        ),
        migrations.CreateModel(
            name="SearchRanking",
            fields=[
                ("ranking_id", models.AutoField(primary_key=True, serialize=False)),
                ("keyword", models.CharField(max_length=255)),
                ("frequency", models.PositiveIntegerField()),
            ],
            options={
                "db_table": "tbl_search_ranking",
            },
        ),
    ]
