# Generated by Django 4.2.7 on 2024-02-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0098_homesearch_searchranking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homesearch",
            name="keywords",
            field=models.TextField(),
        ),
    ]
