# Generated by Django 4.2.7 on 2024-02-27 06:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0099_alter_homesearch_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="searchranking",
            name="frequency",
            field=models.IntegerField(default=1),
        ),
    ]
