# Generated by Django 4.2.7 on 2024-02-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0100_alter_searchranking_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homesearch",
            name="knowledge",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="homesearch",
            name="resources_type",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
