# Generated by Django 4.2.7 on 2024-03-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0101_alter_homesearch_knowledge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resources",
            name="downloads_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="resources",
            name="reactions_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="resources",
            name="shares_count",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="resources",
            name="views_count",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
