# Generated by Django 4.2.7 on 2024-03-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0103_alter_resources_downloads_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutFooter",
            fields=[
                (
                    "about_footer_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("content", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                "db_table": "tbl_about_footer",
            },
        ),
    ]
