# Generated by Django 4.2.7 on 2024-03-12 02:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0104_aboutfooter"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aboutfooter",
            old_name="content",
            new_name="content_footer",
        ),
    ]
