# Generated by Django 4.2.7 on 2024-03-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0105_rename_content_aboutfooter_content_footer"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadVideo",
            fields=[
                ("video_id", models.AutoField(primary_key=True, serialize=False)),
                ("video_title", models.CharField(max_length=255)),
                ("video_path", models.FileField(null=True, upload_to="videos/")),
            ],
            options={
                "db_table": "tbl_video",
            },
        ),
    ]
