# Generated by Django 4.2.7 on 2024-03-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0107_editresourcerequest_date_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editresourcerequest",
            name="date_updated",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
