# Generated by Django 4.2.7 on 2024-03-13 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0108_alter_editresourcerequest_date_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="resources",
            name="bookmark",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_bookmarked_resources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
