# Generated by Django 4.2.7 on 2024-03-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0110_alter_resources_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadvideo",
            name="video_path",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
