# Generated by Django 4.2.7 on 2024-03-21 06:40

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0111_alter_uploadvideo_video_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadvideo",
            name="video_path",
        ),
        migrations.AddField(
            model_name="uploadvideo",
            name="url",
            field=embed_video.fields.EmbedVideoField(default=1),
            preserve_default=False,
        ),
    ]
