# Generated by Django 4.2.7 on 2024-03-26 05:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0113_event"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
    ]
