# Generated by Django 4.2.7 on 2024-03-26 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0115_customuser_feedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="feedback",
        ),
    ]
