# Generated by Django 4.2.7 on 2024-04-01 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0117_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="date_rated",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
