# Generated by Django 4.2.7 on 2024-04-04 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0118_feedback_date_rated"),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("start", models.DateTimeField(blank=True, null=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tbl_events",
            },
        ),
    ]
