# Generated by Django 4.2.7 on 2024-04-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0119_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="end",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="events",
            name="start",
            field=models.DateField(blank=True, null=True),
        ),
    ]
