# Generated by Django 4.2.7 on 2024-04-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0120_alter_events_end_alter_events_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmi",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="cmi",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
