# Generated by Django 4.2.7 on 2024-04-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0121_cmi_latitude_cmi_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmi",
            name="date_joined",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="cmi",
            name="url",
            field=models.URLField(null=True),
        ),
    ]
