# Generated by Django 4.2.7 on 2024-04-12 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0122_cmi_date_joined_cmi_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="CMITeam",
            fields=[
                ("team_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("middle_name", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255, null=True)),
                ("position", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("contact_num", models.CharField(blank=True, max_length=20, null=True)),
                ("date_birth", models.DateField()),
                ("sex", models.CharField(max_length=10)),
                ("bach_deg", models.CharField(max_length=100, null=True)),
                ("db_year_completed", models.DateField(null=True)),
                ("mas_deg", models.CharField(max_length=100, null=True)),
                ("md_year_completed", models.DateField(null=True)),
                ("doc_deg", models.CharField(max_length=100, null=True)),
                ("dd_year_completed", models.DateField(null=True)),
                ("specialization", models.CharField(max_length=255, null=True)),
                ("image", models.ImageField(null=True, upload_to="profiles_img/")),
                ("pds_file", models.FileField(null=True, upload_to="cmi_pds/")),
                ("date_appointed", models.DateField()),
                ("date_created", models.DateField(auto_now_add=True)),
                (
                    "cmi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users_app.cmi"
                    ),
                ),
            ],
            options={
                "db_table": "tbl_cmi_team",
            },
        ),
    ]
