# Generated by Django 4.2.7 on 2024-04-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0124_commodity_latitude_commodity_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmi",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cmi",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=9, null=True
            ),
        ),
        migrations.CreateModel(
            name="TechnologyGenerated",
            fields=[
                ("tech_id", models.AutoField(primary_key=True, serialize=False)),
                ("tech_title", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField()),
                ("generator", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "cmi",
                    models.ManyToManyField(related_name="tech_cmi", to="users_app.cmi"),
                ),
                (
                    "commodity",
                    models.ManyToManyField(
                        related_name="tech_commodity", to="users_app.commodity"
                    ),
                ),
            ],
            options={
                "db_table": "tbl_tech_generated",
            },
        ),
        migrations.CreateModel(
            name="TechnologyAdaptor",
            fields=[
                ("adaptop_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("middle_name", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255, null=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("contact_num", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.CharField(max_length=255, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=9, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=9, max_digits=9, null=True
                    ),
                ),
                ("date_birth", models.DateField()),
                ("sex", models.CharField(max_length=10)),
                ("enterprise", models.CharField(max_length=255, null=True)),
                ("date_adapted", models.DateField()),
                ("date_created", models.DateField(auto_now_add=True)),
                (
                    "technology",
                    models.ManyToManyField(
                        related_name="tech_generated_adaptor",
                        to="users_app.technologygenerated",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_tech_adaptor",
            },
        ),
    ]
