# Generated by Django 4.2.7 on 2024-04-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0125_alter_cmi_latitude_alter_cmi_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmi",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="cmi",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="technologyadaptor",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="technologyadaptor",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=9, null=True
            ),
        ),
    ]
