# Generated by Django 4.2.7 on 2024-04-23 03:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0128_alter_cmi_latitude_alter_cmi_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="technologygenerated",
            name="date_created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
