# Generated by Django 4.2.7 on 2024-04-23 06:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0129_technologygenerated_date_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="technologyadaptor",
            old_name="adaptop_id",
            new_name="adaptor_id",
        ),
    ]
