# Generated by Django 4.2.7 on 2024-04-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0130_rename_adaptop_id_technologyadaptor_adaptor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmi",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="editresourcerequest",
            name="edited_longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="resources",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="technologyadaptor",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
    ]
