# Generated by Django 4.2.7 on 2024-04-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "users_app",
            "0132_remove_customuser_occupation_customuser_contact_num_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="sex",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
