# Generated by Django 4.2.7 on 2024-05-10 02:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0133_alter_customuser_sex"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reaction",
            old_name="dislike",
            new_name="rating",
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="like",
        ),
        migrations.AddField(
            model_name="discussion",
            name="bookmark",
            field=models.ManyToManyField(
                blank=True,
                related_name="user_bookmarked_discussion",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
