# Generated by Django 4.2.7 on 2024-05-10 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0135_reaction_dislike_reaction_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reaction",
            name="dislike",
        ),
        migrations.RemoveField(
            model_name="reaction",
            name="like",
        ),
    ]
