# Generated by Django 4.2.7 on 2024-05-13 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0136_remove_reaction_dislike_remove_reaction_like"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentRating",
            fields=[
                (
                    "comment_rating_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("rating", models.IntegerField(default=1)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users_app.comment",
                    ),
                ),
                (
                    "rated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_comment_rating",
            },
        ),
        migrations.CreateModel(
            name="DiscussionRating",
            fields=[
                (
                    "discussion_rating_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("rating", models.IntegerField(default=1)),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users_app.discussion",
                    ),
                ),
                (
                    "rated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_discussion_rating",
            },
        ),
        migrations.DeleteModel(
            name="Reaction",
        ),
    ]
