# Generated by Django 4.2.7 on 2024-05-14 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0138_comment_react"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscussionReport",
            fields=[
                (
                    "discussion_report_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("report_category", models.CharField(max_length=255)),
                ("report_content", models.TextField(null=True)),
                ("date_reported", models.DateField(default=django.utils.timezone.now)),
                (
                    "discussion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users_app.discussion",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tbl_discussion_report",
            },
        ),
        migrations.CreateModel(
            name="CommentReport",
            fields=[
                (
                    "comment_report_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("report_category", models.CharField(max_length=255)),
                ("report_content", models.TextField(null=True)),
                ("date_reported", models.DateField(default=django.utils.timezone.now)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users_app.comment",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tble_comment_report",
            },
        ),
    ]
