# Generated by Django 4.2.7 on 2024-06-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users_app", "0141_resourcereaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmi",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="commodity",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="editresourcerequest",
            name="edited_latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="resources",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="technologyadaptor",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
    ]
